name: Trigger auto deployment for container-app-dntjv65luyi5q

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-dntjv65luyi5q-AutoDeployTrigger-1b169184-ad2a-4a4a-b732-a204a411217d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPDNTJV65LUYI5Q_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPDNTJV65LUYI5Q_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPDNTJV65LUYI5Q_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPDNTJV65LUYI5Q_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPDNTJV65LUYI5Q_REGISTRY_PASSWORD }}
          containerAppName: container-app-dntjv65luyi5q
          resourceGroup: todotemplate11a3e9
          imageToBuild: default/container-app-dntjv65luyi5q:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


